# Generated by Django 2.2.10 on 2020-08-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200807_1749'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='Artiles',
        ),
        migrations.AlterModelTable(
            name='theme',
            table='Themes',
        ),
    ]
