# Generated by Django 2.2.10 on 2020-08-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200807_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlescope',
            name='is_main',
        ),
        migrations.AddField(
            model_name='theme',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='themes',
            field=models.ManyToManyField(through='articles.ArticleScope', to='articles.Theme'),
        ),
    ]
