# Generated by Django 2.2.10 on 2020-08-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200807_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='is_main',
        ),
        migrations.AddField(
            model_name='articlescope',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
