# Generated by Django 2.2.10 on 2020-08-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200807_1832'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='Articles',
        ),
    ]
